account/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.urls import path
from . import views
from .views import CustomLogoutView, AccountRegisterForm, ProfileView, ProfileEditView
from orders.views import OrderView
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm
from django.contrib.auth.decorators import login_required
app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", CustomLogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", AccountRegisterForm.as_view(), name="register"),
    path("activate/<slug:uidb64>/<slug:token>", views.account_activate, name="activate"),
    # Password reset
    # send email to your mailbox
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_comfirm/",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset/password_reset_email_comfirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
    ),
    # bring you to page for reset email
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="/account/password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset/reset_status.html",
        ),
    ),
    # User profile
    path('profile/', login_required(ProfileView.as_view()), name='profile'),
    path("profile/edit/", login_required(ProfileEditView.as_view()), name="edit_details"),
    path("profile/delete_user/", login_required(ProfileEditView.as_view()), name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/profile/profile_delete_confirmation.html"),
        name="delete_confirmation",
    ),
]

basket/urls.py
from django.urls import path
from . import views
from .views import BasketView
app_name = "basket"
urlpatterns = [
    path("", BasketView.as_view(), name="basket"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("review/", include("review.urls", namespace="review")),
    path("CICD/", include("CICD.urls", namespace="CICD")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views
from .views import OrderView, OrderIssueView
from django.contrib.auth.decorators import login_required
from django.urls import re_path

app_name = "orders"

urlpatterns = [
    path("user_orders/", login_required(OrderView.as_view()), name="user_orders"),
    path("order_issue/<str:order_key>", login_required(OrderIssueView.as_view()), name="order_issue"),
    ]

store/urls.py
from django.urls import path
from . import views
from .views import ProductAll, ProdcutSingle, CategoryProductView

app_name = 'store'

urlpatterns = [
    path('', ProductAll.as_view(), name='store_home'),
    path('product/<slug:slug>', ProdcutSingle.as_view(), name='product_detail'),
    path('store/<slug:category_slug>/', CategoryProductView.as_view(), name='category_list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Store - Low Prices in Books & more{% endblock %}</title>
    <link rel="icon" href="{% static 'core/images/books.png'%}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="{% block sub_base %}{% endblock %}">
    <link rel="stylesheet" href="{% block stylesheet1 %}{% endblock %}">
    <link rel="stylesheet" href="{% block stylesheet2 %}{% endblock %}">
    <link rel="stylesheet" href="{% block stylesheet3 %}{% endblock %}">
</head>

<body>
    <header>
        <nav>
            <div class="nav__content">
                <div>
                    <a href="{% url 'store:store_home' %}">
                        <img class="nav__img--logo" src="{% static 'core/images/sign.png'%}" alt="">
                    </a>
                </div>
                <div class="nav__empty">
                </div>
                <div class="nav__user__bag">
                    {% if user.is_authenticated %}
                    <div class="nav__user">
                        <div class="nav__user__dropdown">
                            <div class="nav__user__dropdown--img">
                                <a href="{% url "account:profile" %}">
                                    <img class="nav__img" src={{ user.profile_img.url }}>
                                </a>
                            </div>
                            <div class="nav__user__dropdown--content">
                                {% if user.is_authenticated %}
                                <div>
                                    <a href="{% url "account:profile" %}">Profile</a>
                                </div>
                                <div>
                                    <a href="{% url 'orders:user_orders' %}">Orders</a>
                                </div>
                                <div>
                                    <a href="{% url 'wishlist:user_wishlist' %}">Wish List</a>
                                </div>
                                <div>
                                    <a href="{% url "account:logout" %}">Logout</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="nav__user">
                        <a href="{% url "account:login" %}">
                            <img class="nav__img" src="{% static 'core/images/user.png' %}" alt="">
                        </a>
                    </div>
                    {% endif %}
                    <div class="nav__bag">
                        <div class="nav__bag--img">
                            <a type="button" role="button" href="{% url "basket:basket" %}">
                                <img class="nav__img" src="{% static 'core/images/bag.png'%}" alt="">
                            </a>
                        </div>
                        {% with total_qty=basket|length %}
                        <div class="nav__bag--number" id="basket-qty">
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}

                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main>
        <div class="warning__block">{% block warning %} {% endblock %}</div>
        <div class="promotion">{% block promotion %} {% endblock %}</div>
        <div class="content"> {% block content %} {% endblock %}</div>
    </main>

    <footer>
        <div class="footer">
            <div class="footer__content">
                <div>
                    <h2>Learn About Us</h2>
                    <ul>
                        <li><a href="#">About Tsao Books</a></li>
                        <li><a href="#">About Our Group</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div>
                    <h2>Member Service</h2>
                    <ul>
                        <li><a href="#">Become Our Members</a></li>
                        <li><a href="#">For New Members</a></li>
                        <li><a href="#">Member Categories</a></li>
                        <li><a href="#">Subscribe to E-Newsletter</a></li>
                        <li><a href="#">Delivery Options</a></li>
                    </ul>
                </div>
                <div>
                    <h2>Collaboration</h2>
                    <ul>
                        <li><a href="#">Corporate Buying</a></li>
                        <li><a href="#">Buy Our Gift Card</a></li>
                        <li><a href="#">Become Our Supplier</a></li>
                        <li><a href="#">Cross Industry Alliance</a></li>
                    </ul>
                </div>
                <div class="">
                    <h2>Customer Service</h2>
                    <ul>
                        <li><a href="#">Forgot ID/Password ?</a></li>
                        <li><a href="#">Connect Us</a></li>
                        <li><a href="#">Help - Q&A List</a></li>
                        <li><a href="#">Live Chat</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer__copyright">
            <div>
                <img src="{% static 'core/images/books.png'%}" alt="">
            </div>
            <div>
                <span>Copyright © 2022 by Tsao Books</span>
            </div>
        </div>
    </footer>
</body>

</html>

templates/sub_base.html
{% extends 'base.html' %}
{% load static %}


{% block sub_base %}
{% static 'core/css/sub_base.css' %}
{% endblock sub_base %}

{% block content %}
<div class="subBaseContent">
    <div class="subBaseContent--title">
        {% block sub_base_title %}{% endblock sub_base_title %}    
    </div>
    <div class="subBaseContent--content">
        {% block sub_base_content %}{% endblock sub_base_content %}
    </div>
</div>
{% endblock content %}