account/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.urls import path
from . import views
from .views import CustomLogoutView, AccountRegisterForm, ProfileView, ProfileEditView
from orders.views import OrderView
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm
from django.contrib.auth.decorators import login_required
app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", CustomLogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", AccountRegisterForm.as_view(), name="register"),
    path("activate/<slug:uidb64>/<slug:token>", views.account_activate, name="activate"),
    # Password reset
    # send email to your mailbox
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_comfirm/",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset/password_reset_email_comfirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
    ),
    # bring you to page for reset email
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="/account/password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset/reset_status.html",
        ),
    ),
    # User profile
    path('profile/', login_required(ProfileView.as_view()), name='profile'),
    path("profile/edit/", login_required(ProfileEditView.as_view()), name="edit_details"),
    path("profile/delete_user/", login_required(ProfileEditView.as_view()), name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/profile/profile_delete_confirmation.html"),
        name="delete_confirmation",
    ),
]

checkout/urls.py
from django.urls import include, path
from . import views
from .views import DeliveryOptionView, PaymentView
from django.contrib.auth.decorators import login_required

app_name = "checkout"

urlpatterns = [
    path("deliveryoptions/", login_required(DeliveryOptionView.as_view()), name="delivery_options"),
    path("payment/", login_required(PaymentView.as_view()), name="payment"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("review/", include("review.urls", namespace="review")),
    path("CICD/", include("CICD.urls", namespace="CICD")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views
from .views import OrderView, OrderIssueView
from django.contrib.auth.decorators import login_required
from django.urls import re_path

app_name = "orders"

urlpatterns = [
    path("user_orders/", login_required(OrderView.as_view()), name="user_orders"),
    path("order_issue/<str:order_key>", login_required(OrderIssueView.as_view()), name="order_issue"),
    ]

store/urls.py
from django.urls import path
from . import views
from .views import ProductAll, ProdcutSingle, CategoryProductView

app_name = 'store'

urlpatterns = [
    path('', ProductAll.as_view(), name='store_home'),
    path('product/<slug:slug>', ProdcutSingle.as_view(), name='product_detail'),
    path('store/<slug:category_slug>/', CategoryProductView.as_view(), name='category_list'),
]

checkout/models.py
from re import M
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class DeliveryOptions(models.Model):
    """
    The Delivery methods table containing all delivery
    """

    DELIVERY_COHICES = [
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
        ("DD", "Digital Delivery"),
    ]

    delivery_name = models.CharField(verbose_name=_("delivery_name"), help_text=_("Required"), max_length=255)

    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99"),
            },
        },
        max_digits=5,
        decimal_places=2,
    )

    delivery_method = models.CharField(
        choices=DELIVERY_COHICES,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )

    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )

    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
    Store payment option
    """

    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

checkout/views.py
import json

# django
from django.http import HttpResponseRedirect, JsonResponse, QueryDict
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View, ListView, TemplateView

# local app
from checkout.models import DeliveryOptions, PaymentSelections
from basket.basket import Basket
from account.models import Address
from orders.models import Order, OrderItem
from store.models import Product

# paypal
from checkout.paypal import PayPalClient
from paypalcheckoutsdk.orders import OrdersGetRequest

# Views


class DeliveryOptionView(ListView):
    model = DeliveryOptions
    template_name = "checkout/delivery_choices.html"

    def get_context_object_name(self, object_list):
        return "delivery_options"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["deliveryoptions"] = DeliveryOptions.objects.filter(is_active=True)
        return context

    def put(self, request):
        # Update delivery options
        basket = Basket(request)
        delivery_option = int(QueryDict(request.body)["deliveryoption"])
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = basket.basket_update_delivery(delivery_type.delivery_price)

        session = request.session
        if "purchase" not in request.session:
            session["purchase"] = {"delivery_id": delivery_type.id}
        else:
            session["purchase"]["delivery_id"] = delivery_type.id
            session.modified = True

        response = JsonResponse(
            {
                "total": updated_total_price,
                "delivery_price": delivery_type.delivery_price,
            }
        )
        return response


# class DeliveryAddressView(View):
    
#     def get(self, request):
#         session = request.session
#         if "purchase" not in request.session:
#             messages.success(request, "Please select delivery option")
#             return HttpResponseRedirect(request.META["HTTP_REFERER"])

#         try:
#             self.address = Address.objects.get(customer_id=request.user.id)

#         except ObjectDoesNotExist:
#             return render(request, "checkout/delivery_address.html")

#         else:
#             if "address" not in request.session:
#                 session["address"] = {"address_id": str(self.address)}
#             else:
#                 session["address"]["address_id"] = str(self.address)
#                 session.modified = True
#             return render(
#                 request,
#                 "checkout/delivery_address.html",
#                 context={
#                     "address": self.address,
#                 },
#             )

class PaymentView(View):

    def get(self, request):

        session = request.session
        address = Address.objects.get(customer_id=request.user.id)
        if "purchase" not in request.session:
            messages.success(request, "Please select delivery option")
            return HttpResponseRedirect(request.META["HTTP_REFERER"])

        else:
            if "address" not in request.session:
                session["address"] = {"address_id": str(address)}
            else:
                session["address"]["address_id"] = str(address)
                session.modified = True

        return render(request, "checkout/payment_selection.html", context={"address": address})

    def post(self, request):
        user_id = request.user.id
        body = json.loads(request.body)
        # get payment source
        payment_source = body["paymentSource"]
        payment_instance = PaymentSelections.objects.get(name=payment_source)

        # send a request to paypal to fetch order information
        PPClient = PayPalClient()
        data = body["orderID"]
        requestorder = OrdersGetRequest(data)
        response = PPClient.client.execute(requestorder)

        # basket instance
        basket = Basket(request)

        # address instance
        address_instance = Address.objects.get(customer_id=user_id)

        # delivery option instance
        delivery_id = request.session["purchase"]["delivery_id"]
        delivery_instance = DeliveryOptions.objects.get(id=int(delivery_id))

        order = Order.objects.create(
            user_id=user_id,
            address=address_instance,
            payment_option=payment_instance,
            delivery_option=delivery_instance,
            email=response.result.payer.email_address,
            total_paid=response.result.purchase_units[0].amount.value,
            order_key=response.result.id,
            billing_status=True,
        )

        # save order item
        for item in basket:
            OrderItem.objects.create(order=order, product=item["product"], quantity=item["qty"])

        return JsonResponse("Payment complete!", safe=False)


@login_required
def payment_successful(request):
    basket = Basket(request)
    # update inventory
    product_ids = basket.basket.keys()
    products = Product.objects.filter(id__in=product_ids)
    for product in products:
        product.inventory -= basket.basket[str(product.id)]["qty"]
        product.save()

    basket.clear()
    return render(request, "checkout/payment_successful.html", {})

templates/checkout/delivery_address.html
{% extends 'sub_base.html' %}
{% load static %}

{% block title %}
Delivery Address
{% endblock title %}

{% block stylesheet1 %}
{% static 'checkout/css/checkout_address.css' %}
{% endblock stylesheet1 %}

{% block sub_base_title %}
<div class="deliveryAddress__title">
  Delivery Address
</div>
{% endblock %}
{% block sub_base_content %}

<div class="deliveryAddress">
    {% if not address %}
    <div class="col-12">There are no delivery addresses,
      <a href="{% url 'account:edit_details' %}">
        Edit your address in your profile
      </a>
    </div>
    {% else %}
    <div data-index="{{option.id}}">
      <div class="deliveryAddress__detail">
        <div class="deliveryAddress__detail__content">
          <div class="deliveryAddress__detail__content--title">
            Full name:
          </div>
          <div class="deliveryAddress__detail__content--content">
            {{address.full_name}}
          </div>
        </div>
        <div class="deliveryAddress__detail__content">
          <div class="deliveryAddress__detail__content--title">
            Address Line 1:
          </div>
          <div class="deliveryAddress__detail__content--content">
            {{address.address_line}}
          </div>
        </div>
        <div class="deliveryAddress__detail__content">
          <div class="deliveryAddress__detail__content--title">
            Address Line 2:
          </div>
          <div class="deliveryAddress__detail__content--content">
            {{address.address_line2}}
          </div>
        </div>
        <div class="deliveryAddress__detail__content">
          <div class="deliveryAddress__detail__content--title">
            Town & City:
          </div>
          <div class="deliveryAddress__detail__content--content">
            {{address.town_city}}
          </div>
        </div>
        <div class="deliveryAddress__detail__content">
          <div class="deliveryAddress__detail__content--title">
            Postcode:
          </div>
          <div class="deliveryAddress__detail__content--content">
            {{address.postcode}}
          </div>
        </div>
        <div class="deliveryAddress__detail__content">
          <div class="deliveryAddress__detail__content--title">
            Country:
          </div>
          <div class="deliveryAddress__detail__content--content">
            {{address.country.name}}
          </div>
        </div>
        <div class="deliveryAddress__detail__content">
          <div class="deliveryAddress__detail__content--title">
            Phone number:
          </div>
          <div class="deliveryAddress__detail__content--content">
            {{address.phone}}
          </div>
        </div>
        <div class="deliveryAddress__detail__content--edit">
          <a href="{% url 'account:edit_details'%}" class="text-decoration-none">
            <button>
              Edit    
            </button>
          </a>
          </div>
      </div>
    </div>
  <div>
    <div>
      <div>Sub Total:</div>
      <div>
        <span>$ </span>
        <span id="sub_total">
          {{basket.get_subtotal_price_after_tax}}
        </span>
      </div>
      <div>
        <div>Delivery Cost:</div>
        <div>
          <span>$ </span>
          <span id="delivery_price">
            {{basket.get_delivery_price}}
          </span>
        </div>
      </div>
      <div>
        <div>Total:</div>
        <div>
          <span>$ </span>
          <span id="total">
            {{basket.get_total_price}}
          </span>
        </div>
      </div>
      <a role="button" href="{% url 'checkout:payment' %}">
        <button>
          Pay Securely
        </button>
      </a>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/checkout/delivery_choices.html
{% extends 'sub_base.html' %}
{% load static %}

{% block title %}
Delivery Options
{% endblock title %}

{% block stylesheet1 %}
{% static 'checkout/css/checkout.css' %}
{% endblock stylesheet1 %}

{% block sub_base_title %}
<div class="deliveryOption__title">
    <div class="deliveryOption__bean__home">
        <a href="{% url 'store:store_home' %}"> Home </a>
    </div>
    <div class="deliveryOption__bean__current">
        Delivery Options
    </div>
</div>
{% endblock %}
{% block sub_base_content %}
<div class="deliveryoptions">
    {% if messages %}
    <div class="warning" alert-"{{ message.tags }}" role="alert">
        {% for message in messages  %}
        {{message|safe}}
        {% endfor %}
    </div>
    {% endif %}
    <div class="deliveryoptions__content">
        {% if delivery_options|length  == 0 %}
        <div>There are no delivery options avaliable <a href="{% url 'store:store_home' %}">Shop</a></div>
        {% else %}
        <div>
            {% for option in delivery_options %}
            {% if option.id == request.session.purchase.delivery_id %}
            <div class="deliveryOption__option checked--background" data-index="{{option.id}}">
                <label class="deliveryOption__option__label" for="{{option.id}}">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                            <path
                                d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                        </svg>
                    </div>
                    <div class="deliveryOption__nameDescription">
                        <div class="deliveryOption__name">{{option.delivery_name}}</div>
                        <div class="deliveryOption__description">
                            Your order should be delivered within {{option.delivery_timeframe}}.
                        </div>
                    </div>
                </label>
                <input type="radio" name="deliveryOption" id="{{option.id}}" value="{{option.id}}" checked>
            </div>
            {% else %}
            <div class="deliveryOption__option" data-index="{{option.id}}">
                <label class="deliveryOption__option__label" for="{{option.id}}">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                            <path
                                d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                        </svg>
                    </div>
                    <div class="deliveryOption__nameDescription">
                        <div class="deliveryOption__name">{{option.delivery_name}}</div>
                        <div class="deliveryOption__description">
                            Your order should be delivered within {{option.delivery_timeframe}}.
                        </div>
                    </div>
                </label>
                <input type="radio" name="deliveryOption" id="{{option.id}}" value="{{option.id}}">
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="deliveryOption__total">
            <div class="deliveryOption__total__subtotal">
                <div class="deliveryOptionn__total__title">Sub Total:</div>
                <div class="deliveryOptionn__total__price"><span>$ </span><span id="sub_total">{{basket.get_subtotal_price_after_tax}}</span></div>
            </div>
            <div class="deliveryOption__total__deliverycost">
                <div class="deliveryOptionn__total__title">Delivery Cost:</div>
                <div class="deliveryOptionn__total__price">
                    <span>$ </span=><span id="delivery_price">{{basket.get_delivery_price}}</span>
                </div>
            </div>
            <div class="deliveryOption__total__total">
                <div class="deliveryOptionn__total__title">Total:</div>
                <div class="deliveryOptionn__total__price"><span>$ </span=><span id="total">{{basket.get_total_price}}</span></div>
            </div>
            <div class="deliveryOption__total__paybutton">
                <a role="button" href=" {% url 'checkout:payment' %}">
                    <button>
                        Pay Securely
                    </button>
                </a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
</div>

<script>
    $(document).ready(function () {
        var options = new Array();
        options[0] = "{{request.session.purchase.delivery_id}}"
        $('input[type=radio][name=deliveryOption]').on('change', function (e) {
            var deliveryoption = $(this).val()
            options.push(deliveryoption)

            // remove unused record
            if (options.length >= 3) {
                options.shift()
            }
            $('input[id="' + options[options.length - 2] + '"]').removeAttr('checked')
            $.ajax({
                headers: {
                    'X-CSRFTOKEN': '{{ csrf_token }}',
                },
                type: "PUT",
                url: '{% url "checkout:delivery_options" %}',
                data: {
                    deliveryoption: deliveryoption,
                    action: "create-update-delivery-option-in-session",
                },
                success: function (json) {
                    document.getElementById("total").innerHTML = json.total
                    document.getElementById("delivery_price").innerHTML = json
                        .delivery_price

                    // remove previous checked background and color new selected option
                    $('.deliveryOption__option[data-index="' + deliveryoption + '"]')
                        .addClass("checked--background")
                    $('input[id="' + deliveryoption + '"]').prop("checked")
                    $('.deliveryOption__option[data-index="' + options[(options.length -
                        2)] + '"]').removeClass("checked--background")
                },
                error: function (xhr, errmsg, err) {},
            })
        })
    })
</script>
{% endblock %}

templates/checkout/payment_selection.html
{% extends 'sub_base.html' %}
{% load static %}
{% load product_filter %}

{% block title %}
Payment Selection
{% endblock title %}

{% block stylesheet1 %}
{% static 'checkout/css/payment.css' %}
{% endblock stylesheet1 %}

{% block sub_base_title %}
<div class="basket__title">
    <div class="basket__bean__home">
        <a href="{% url 'store:store_home' %}"> Home </a>
    </div>
    <div class="basket__bean__bag">
        Payment Selection
    </div>
</div>
{% endblock %}

{% block sub_base_content %}
<div class="addressPayment">
    <div class="deliveryAddress">
        <div class="deliveryAddress_title">Shipping info.</div>
        <div class="deliveryAddress__detail">
            <div class="deliveryAddress__detail__content">
                <div class="deliveryAddress__detail__content--title">
                    Full name:
                </div>
                <div class="deliveryAddress__detail__content--content">
                    {{address.full_name}}
                </div>
            </div>
            <div class="deliveryAddress__detail__content">
                <div class="deliveryAddress__detail__content--title">
                    Address Line 1:
                </div>
                <div class="deliveryAddress__detail__content--content">
                    {{address.address_line}}
                </div>
            </div>
            <div class="deliveryAddress__detail__content">
                <div class="deliveryAddress__detail__content--title">
                    Address Line 2:
                </div>
                <div class="deliveryAddress__detail__content--content">
                    {{address.address_line2}}
                </div>
            </div>
            <div class="deliveryAddress__detail__content">
                <div class="deliveryAddress__detail__content--title">
                    Town & City:
                </div>
                <div class="deliveryAddress__detail__content--content">
                    {{address.town_city}}
                </div>
            </div>
            <div class="deliveryAddress__detail__content">
                <div class="deliveryAddress__detail__content--title">
                    Postcode:
                </div>
                <div class="deliveryAddress__detail__content--content">
                    {{address.postcode}}
                </div>
            </div>
            <div class="deliveryAddress__detail__content">
                <div class="deliveryAddress__detail__content--title">
                    Country:
                </div>
                <div class="deliveryAddress__detail__content--content">
                    {{address.country.name}}
                </div>
            </div>
            <div class="deliveryAddress__detail__content">
                <div class="deliveryAddress__detail__content--title">
                    Phone number:
                </div>
                <div class="deliveryAddress__detail__content--content">
                    {{address.phone}}
                </div>
            </div>
            <div class="deliveryAddress__detail__content--edit">
                <a href="{% url 'account:edit_details'%}">
                    <button>
                        Edit
                    </button>
                </a>
            </div>
        </div>
    </div>
    <div class="payment__summaryPaypal">
        <div class="payment__summary">
            <div class="payment__summary__subsection">
                <div class="payment__title">Sub Total:</div>
                <div class="payment__price">
                    $ {{basket.get_subtotal_price_before_tax}}
                </div>
            </div>
            <div class="payment__summary__subsection" >
                <div class="payment__title">Delivery Cost:</div>
                <div class="payment__price">
                    $ {{basket.get_delivery_price}}
                </div>
            </div>

            <div class="payment__summary__subsection" id="totalCost">
                <div class="payment__title">Total:</div>
                <div class="payment__price">
                    $ {{basket.get_total_price}}
                </div>
            </div>
        </div>
        <div class="paypal__button">
            <div id="paypal-button-container"></div>
        </div>
    </div>
</div>




<script
    src="https://www.paypal.com/sdk/js?client-id=AWrNAL-sz_i_Ntao5-i9aJ_93mvrPbkJsbyGq8OvKHQPpXsbGfLNlwm8yZM8huA1GYouhZIkPEBuxYdy&currency=USD&disable-funding=credit,card"
    data-sdk-integration-source="button-factory">
</script>
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function initPayPalButton() {
        paypal.Buttons({
            style: {
                shape: 'rect',
                color: 'gold',
                layout: 'vertical',
                label: 'paypal',
            },
            onClick: (data) => {
                var fundingSource = data.fundingSource;
            },
            createOrder: function (data, actions) {
                return actions.order.create({
                    application_context: {
                        brand_name: 'Bookstore',
                        locale: 'us-US',
                        shipping_preference: 'SET_PROVIDED_ADDRESS',
                    },
                    purchase_units: [{
                        amount: {
                            "currency_code": "USD",
                            "value": '{{basket.get_total_price}}'
                        },
                        shipping: {
                            name: {
                                full_name: '{{ address.full_name }}'
                            },
                            address: {
                                address_line_1: '{{ address.address_line }}',
                                address_line_2: '{{ address.address_line2 }}',
                                admin_area_2: '{{ address.town_city }}',
                                postal_code: '{{ address.postcode }}',
                                country_code: '{{ address.country }}',
                            }
                        }
                    }]
                });
            },
            onApprove: function (data) {
                var url = "{% url 'checkout:payment' %}";
                return fetch(url, {
                    method: 'POST',
                    headers: {
                        'content-type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify({
                        orderID: data.orderID,
                        paymentSource: data.paymentSource,
                    })
                }).then(function () {
                    location.href = "{% url 'checkout:payment_successful' %}";
                })
            },
        }).render('#paypal-button-container');
    }
    initPayPalButton();
</script>
{% endblock %}

templates/checkout/payment_successful.html
{% extends 'sub_base.html' %}
{% load static %}
{% load product_filter %}

{% block title %}
Payment Selection
{% endblock title %}

{% block stylesheet1 %}
{% static 'checkout/css/payment.css' %}
{% endblock stylesheet1 %}


{% block sub_base_content %}

<div class="paymentSuccess">
  <div class="paymentSuccess__thankyou">
    Thank you for choosing Tsao Books!
  </div>
  <div class="paymentSuccess__redirect">
    Redirect to <a href="{% url 'orders:user_orders' %}">Orders</a> in <span id="countmesg"></span>
  </div>
</div>

<script>
  $(document).ready(function () {
      var delay = 10;
      var url = "{% url 'orders:user_orders' %}";
      var timer = null

      function countdown() {
          timer = setTimeout(countdown, 1000);
          $('#countmesg').html(delay + " seconds.");
          delay--;
          if (delay < 0) {
              clearTimeout(timer);
              window.location = url;
              delay = 0;
          }
      }
      countdown();
  });
</script>

{% endblock %}