account/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.urls import path
from . import views
from .views import CustomLogoutView, AccountRegisterForm, ProfileView, ProfileEditView
from orders.views import OrderView
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm
from django.contrib.auth.decorators import login_required
app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", CustomLogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", AccountRegisterForm.as_view(), name="register"),
    path("activate/<slug:uidb64>/<slug:token>", views.account_activate, name="activate"),
    # Password reset
    # send email to your mailbox
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_comfirm/",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset/password_reset_email_comfirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
    ),
    # bring you to page for reset email
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="/account/password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset/reset_status.html",
        ),
    ),
    # User profile
    path('profile/', login_required(ProfileView.as_view()), name='profile'),
    path("profile/edit/", login_required(ProfileEditView.as_view()), name="edit_details"),
    path("profile/delete_user/", login_required(ProfileEditView.as_view()), name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/profile/profile_delete_confirmation.html"),
        name="delete_confirmation",
    ),
]

basket/urls.py
from django.urls import path
from . import views
from .views import BasketView
app_name = "basket"
urlpatterns = [
    path("", BasketView.as_view(), name="basket"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("review/", include("review.urls", namespace="review")),
    path("CICD/", include("CICD.urls", namespace="CICD")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views
from .views import ReviewView
from django.contrib.auth.decorators import login_required

app_name = "review"

urlpatterns = [
    path("", login_required(ReviewView.as_view()), name="post_review"),
]

store/urls.py
from django.urls import path
from . import views
from .views import ProductAll, ProdcutSingle, CategoryProductView

app_name = 'store'

urlpatterns = [
    path('', ProductAll.as_view(), name='store_home'),
    path('product/<slug:slug>', ProdcutSingle.as_view(), name='product_detail'),
    path('store/<slug:category_slug>/', CategoryProductView.as_view(), name='category_list'),
]

wishlist/urls.py
from django.urls import path
from . import views
from .views import WishListView
from django.contrib.auth.decorators import login_required

app_name = 'wishlist'

urlpatterns = [
    path('user_wishlist/', login_required(WishListView.as_view()), name='user_wishlist'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class Author(models.Model):
    full_name = models.CharField(max_length=255, blank=False)

    def __str__(self):
        return self.full_name


class Image(models.Model):
    image = models.ImageField(upload_to="images/product_img/", default="images/product_img/product_default.png")
    image_name = models.CharField(max_length=255, blank=False, default="book_img")

    def __str__(self):
        return self.image_name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="product", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.ManyToManyField(Author, related_name="product_author")
    description = models.TextField(blank=True)
    image = models.ForeignKey(Image, on_delete=models.CASCADE, related_name="product_image")
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    inventory = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    click_counter = models.IntegerField(default=0)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "Products"
        ordering = ("-created",)

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title


class Promotion(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="images/promotion_img/", null=True, blank=True)

    def __str__(self):
        return self.name

store/views.py
import json
from django.http import HttpResponse, JsonResponse, QueryDict
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404, render
from django.core.exceptions import ObjectDoesNotExist

# local app
from store.products import ProductPaginator, random_background_image, ProductTools
from store.models import Category, Product, Promotion
from review.models import Review
from review.forms import ReviewForm
from orders.models import Order
from orders.models import OrderItem

# templatetag function
from store.templatetags.product_filter import ratingaverage, ratingaverage_fill

# Views


class ProductAll(ListView):
    template_name = "store/index.html"
    model = Product

    def get(self, request, *args, **kwargs):
        # override get
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, "exists"):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(
                    _("Empty list and “%(class_name)s.allow_empty” is False.")
                    % {
                        "class_name": self.__class__.__name__,
                    }
                )
        # get context data
        context = self.get_context_data()

        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            response = {"product_inf": {}, "pages": context["num_pages"]}
            for product in context["all_product_paginated"].object_list:
                product_dict = {}
                product_dict["slug"] = product.slug
                product_dict["url"] = product.get_absolute_url()
                product_dict["image_url"] = product.image.image.url
                product_dict["title"] = product.title
                product_dict["authors"] = list(product.author.all().values_list("full_name", flat=True))
                product_dict["price"] = product.price
                product_dict["rating"] = str(ratingaverage(product.id))
                product_dict["rating_transfer"] = ratingaverage_fill(product.id)
                response["product_inf"][product.id] = product_dict
            return JsonResponse(response)

        return self.render_to_response(context)

    def patch(self, request):
        # plus one in product click_counter when user click
        slug = QueryDict(request.body)["slug"]
        product = get_object_or_404(Product, slug=slug, in_stock=True)
        product.click_counter += 1
        product.save()

        return HttpResponse(status=200)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_num = self.request.GET.get("page", 1)
        # all product pagination
        all_product = Product.objects.all().order_by("id")

        # all product
        all_product_paginated = ProductPaginator(all_product).paginate(page_num, item_per_page=6)
        context["num_pages"] = all_product_paginated["num_pages"]
        context["all_product_paginated"] = all_product_paginated["paginated_object"]

        # popular product in index
        popular_product = Product.objects.all().order_by("-click_counter")[:5]
        context["popular_product"] = popular_product

        # category list
        context["categories"] = Category.objects.all()

        # promotion
        context["promotions"] = Promotion.objects.all()

        return context


class CategoryProductView(ListView):
    template_name = "store/category.html"
    model = Category

    def get(self, request, *args, **kwargs):
        # override get
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, "exists"):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(
                    _("Empty list and “%(class_name)s.allow_empty” is False.")
                    % {
                        "class_name": self.__class__.__name__,
                    }
                )
        # get context data
        context = self.get_context_data()

        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            response = {"product_inf": {}, "pages": context["num_pages"]}
            for product in context["category_all_product_paginated"].object_list:
                product_dict = {}
                product_dict["slug"] = product.slug
                product_dict["url"] = product.get_absolute_url()
                product_dict["image_url"] = product.image.image.url
                product_dict["title"] = product.title
                product_dict["authors"] = list(product.author.all().values_list("full_name", flat=True))
                product_dict["price"] = product.price
                product_dict["rating"] = str(ratingaverage(product.id))
                product_dict["rating_transfer"] = ratingaverage_fill(product.id)
                response["product_inf"][product.id] = product_dict
            return JsonResponse(response)

        return self.render_to_response(context)

    def get_queryset(self, *args, **kwargs):
        category = Category.objects.get(slug=self.kwargs["category_slug"])
        products = Product.objects.filter(category=category)
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_num = self.request.GET.get("page", 1)
        # Category all product pagination
        category_all_product_paginated = ProductPaginator(self.object_list).paginate(page_num, item_per_page=6)
        context["num_pages"] = category_all_product_paginated["num_pages"]
        context["category_all_product_paginated"] = category_all_product_paginated["paginated_object"]

        # category name and all category list
        context["category"] = Category.objects.get(slug=self.kwargs["category_slug"])
        context["categories"] = Category.objects.all()
        context["category_background"] = random_background_image()

        # popular product
        popular_product = Product.objects.all().order_by("-click_counter")[:5]
        context["popular_product"] = popular_product
        return context


class ProdcutSingle(DetailView):
    model = Product
    template_name = "store/single.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id
        # preparing extra context data
        product = self.object
        _range = ProductTools(product).quantity_range()
        review_all = Review.objects.filter(product=product.id)
        review_form = ReviewForm()
        context = {**context, **{"product": product, "range": _range, "review_all": review_all}}
        # Check wether current user had buy this product
        user_id = self.request.user.id
        # order_ids of current user
        user_order_id = Order.objects.filter(user_id=user_id)
        # all kind of product that user had buy
        user_order_items = (
            OrderItem.objects.filter(order_id__in=user_order_id).values_list("product_id", flat=True).distinct()
        )
        # Render review_form if user had buy this product
        if product.id in user_order_items:
            try:
                current_user_left_review = Review.objects.get(reviewer=user_id, product=product.id)
            except ObjectDoesNotExist:
                context["review_form"] = review_form
            else:
                context = context

        else:
            # if user has lefted review in this product, then don't show review form
            context = context

        return context

templates/store/home.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}Bookstore{% endblock title %}

{% block content %}
<main>
    <div class="container">
        <div class="alert alert-primary fw600 rounded-0 border-0 py-3" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                class="bi bi-info-circle me-2" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                <path
                    d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
            </svg>
            COVID-19 - <u>Click here for our latest updates</u> on our stores, website and contact centre. Thank you for
            your patience and support.
        </div>

        <div class="album py-5 bg-light">
            <div class="container">
                <div class="pb-3 h5">All Books</div>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

                    {% for product in products %}

                    <div class="col">
                        <div class="card shadow-sm">
                            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                            <div class="card-body">
                                <p class="card-text">
                                    <a class="text-dark text-decoration-none"
                                        href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">9min read</small>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}

                </div>
            </div>
        </div>


</main>
{% endblock content %}

templates/store/single.html
{% extends "base.html" %}
{% load static %}
{% load product_filter %}
{% load author_filter %}

{% block stylesheet1 %}
{% static 'store/css/store.css' %}
{% endblock stylesheet1 %}

{% block stylesheet2 %}
{% static 'store/css/single.css' %}
{% endblock stylesheet2 %}

{% block stylesheet3 %}
{% static 'review/css/review.css' %}
{% endblock stylesheet3 %}


{% block title %}
{% if product %}{{ product.title }}{% else %}Products{% endif %}
{% endblock %}


{% block content %}
<div class="indexTitle__bean">
    <div class="indexTitle__bean__home">
        <a href="{% url 'store:store_home' %}"> Home </a>
    </div>
    <div class="indexTitle__bean__category">
        <a href="{% url 'store:category_list' category_slug=product.category.slug %}"> {{ product.category.name }}
        </a>
    </div>
    <div class="indexTitle__bean__product">
        {{ product.title }}
    </div>
</div>
<div class="single">
    <div class="productSingle">
        <div class="productSingle__info">
            <div class="productSingle__img">
                <div class="productSingle__img--image">
                    <a href="{{product.get_absolute_url}}">
                        <img alt="Responsive image" src="{{ product.image.image.url }}">
                    </a>
                </div>
                <div class="productSingle__img--background">
                </div>
            </div>
            <div class="productSingle__content">
                <div class="productSingle__Title">
                    {{ product.title }}
                </div>
                <div class="productSingle__Author">
                    By
                    {% for author in product.author.all|authorsin3 %}
                    {{ author }}
                    {% endfor %}
                </div>
                <div class="productSingle__Description">
                    Description
                </div>
                <div class="productSingle__Description__content">
                    {{ product.description }}
                </div>
            </div>
            <div class="productSingle__addItem">
                <div class="addItem__priceQuantity">
                    <div class="addItem__price">
                        <div class="addItem__price--price">
                            $ {{ product.price }}
                        </div>
                        <div class="beforeTax">
                            (before tax)
                        </div>
                    </div class="addItem__Quantity--select">
                    <div class="quantity">
                        {% with qty=product.inventory %}
                        {% if qty == 0 %}
                        <div>Out of stock!</div>
                        {% else %}
                        <a class="isDisabled" id="decreaseQty_anchor">
                            <div class="decreaseQty">
                                <svg version="1.1" id="arrow-left" xmlns="http://www.w3.org/2000/svg"
                                    xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 330 330"
                                    style="enable-background:new 0 0 330 330;" xml:space="preserve">
                                    <path id="XMLID_26_"
                                        d="M315,0H15C6.716,0,0,6.716,0,15v300c0,8.284,6.716,15,15,15h300c8.284,0,15-6.716,15-15V15
                               C330,6.716,323.284,0,315,0z M255,180H75c-8.284,0-15-6.716-15-15s6.716-15,15-15h180c8.284,0,15,6.716,15,15S263.284,180,255,180z" />
                                </svg>
                            </div>
                        </a>
                        <div class="quantity--quantity">1</div>
                        <a>
                            <div class="increaseQty" id="increaseQty_anchor">
                                <svg version="1.1" id="arrow-right" xmlns="http://www.w3.org/2000/svg"
                                    xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 330 330"
                                    style="enable-background:new 0 0 330 330;" xml:space="preserve">
                                    <path id="XMLID_23_"
                                        d="M315,0H15C6.716,0,0,6.716,0,15v300c0,8.284,6.716,15,15,15h300c8.284,0,15-6.716,15-15V15
                               C330,6.716,323.284,0,315,0z M255,180h-75v75c0,8.284-6.716,15-15,15s-15-6.716-15-15v-75H75c-8.284,0-15-6.716-15-15
                               s6.716-15,15-15h75V75c0-8.284,6.716-15,15-15s15,6.716,15,15v75h75c8.284,0,15,6.716,15,15S263.284,180,255,180z" />
                                </svg>

                            </div>
                        </a>
                        {% endif %}
                        {% endwith %}
                    </div>
                </div>
                <div class="addItem__basketWishlist">
                    {% if product.inventory == 0 %}
                    <div class="addItem__addtoBasket">
                        <button class="isDisabled" type="button" id="add-button" value="{{product.id}}">Add to basket
                        </button>
                    </div>
                    {% else %}
                    <div class="addItem__addtoBasket">
                        <button type="button" id="add-button" value="{{product.id}}">
                            Add to basket
                        </button>
                    </div>
                    {% endif %}
                    <div class="addItem__addtoWishlist">
                        <button type="button" id="add-button-wishlist" value="{{product.id}}">
                            Add to Wish List
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="review">
    {% if review_form %}
    <div class="review_form">
        <div class="reviewForm__title">Hi <span class="username">{{user.get_username}}</span>, leave a review:</div>
        <form id="review-form" action="#" method="POST">
            {% csrf_token %}
            <div class="rating">
                <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
                <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
                <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
                <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
                <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
            </div>
            <div class="form-outline">
                {{ review_form.review_text }}
            </div>
            <div class="reviewSubmit">
                <button class="" id="review-submit">
                    Submit
                </button>
            </div>
        </form>
    </div>
    {% endif %}
    <br>
    <hr>
    <br>
    <div class="review__title">
        Reviews
    </div>
    {% if not review_all %}
    <div class="review-empty">
        There is no review currently.
    </div>
    {% endif %}
    {% for review in review_all %}
    <div class="review_all">
        <div class="reviewer">
            <div class="reviewer__image">
                <img src="{{review.reviewer.profile_img.url}}">
            </div>
            <div class="reviewer__right">
                <div class="reviewer__username">
                    {{review.reviewer.user_name}}
                </div>
                <div class="reviewer__ratingtime">
                    <div class="reviewer__rating">
                        <div class="productAll__info__rating__stars">
                            <div class="productAll__info__rating__stars__container"
                                style="width:{{ review.rating|inttopercent }}%;">
                                <div class="productAll__info__rating__stars--fill">
                                    <div class="starYellow"><img src="{% static 'core/images/star_yellow.png' %}"
                                            alt="">
                                    </div>
                                    <div class="starYellow"><img src="{% static 'core/images/star_yellow.png' %}"
                                            alt="">
                                    </div>
                                    <div class="starYellow"><img src="{% static 'core/images/star_yellow.png' %}"
                                            alt="">
                                    </div>
                                    <div class="starYellow"><img src="{% static 'core/images/star_yellow.png' %}"
                                            alt="">
                                    </div>
                                    <div class="starYellow"><img src="{% static 'core/images/star_yellow.png' %}"
                                            alt="">
                                    </div>
                                </div>
                            </div>
                            <div class="productAll__info__rating__stars--empty">
                                <div class="starEmpty"><img src="{% static 'core/images/star_empty.png' %}" alt="">
                                </div>
                                <div class="starEmpty"><img src="{% static 'core/images/star_empty.png' %}" alt="">
                                </div>
                                <div class="starEmpty"><img src="{% static 'core/images/star_empty.png' %}" alt="">
                                </div>
                                <div class="starEmpty"><img src="{% static 'core/images/star_empty.png' %}" alt="">
                                </div>
                                <div class="starEmpty"><img src="{% static 'core/images/star_empty.png' %}" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="reviewer__posttime">
                        {{review.post_time|daymonthyears}}
                    </div>
                </div>
            </div>

        </div>
        <div class="review_text">
            {{review.review_text}}
        </div>
    </div>
    {% endfor %}
</div>



<script>
    $(document).on('click', '.decreaseQty', function (e) {
        var current_quantity = $('.quantity--quantity').text();
        current_quantity = parseInt(current_quantity);

        if (current_quantity - 1 <= 1) {
            $('.quantity--quantity').html(current_quantity - 1);
            $('#decreaseQty_anchor').addClass("isDisabled");
            $('#increaseQty_anchor').removeClass("isDisabled");
            
        } else {
            $('.quantity--quantity').html(current_quantity - 1);
            $('#increaseQty_anchor').removeClass("isDisabled");
        };

    })

    $(document).on('click', '.increaseQty', function (e) {
        var current_quantity = $('.quantity--quantity').text();
        var product_inventory = "{{product.inventory}}";
        current_quantity = parseInt(current_quantity);
        product_inventory = parseInt(product_inventory);
        
         $('.quantity--quantity').html(current_quantity + 1)

        if (current_quantity + 1 >= product_inventory) {
            $('.quantity--quantity').html(current_quantity + 1);
            $('#increaseQty_anchor').addClass("isDisabled");
            $('#decreaseQty_anchor').removeClass("isDisabled");

        } else if (current_quantity + 1 >= 2) {
            $('.quantity--quantity').html(current_quantity + 1);
            $('#decreaseQty_anchor').removeClass("isDisabled");
        };

    })

    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        var current_quantity = parseInt($('.quantity--quantity').text());
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: current_quantity,
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'add-product-to-basket'
            },
            success: function (json) {
                document.getElementById('basket-qty').innerHTML = json.qty;
            },
            error: function (xhr, errmsg, err) {

            }
        });

    })

    $(document).on('click', '#add-button-wishlist', function (e) {
        e.preventDefault();
        $.ajax({
            headers: {
                'X-CSRFTOKEN': '{{ csrf_token }}'
            },
            type: 'PUT',
            url: '{% url "wishlist:user_wishlist" %}',
            data: {
                productid: $('#add-button-wishlist').val(),
                action: 'add-to-user-wishlist'
            },
            success: function (json) {

            },
            error: function (xhr, errmsg, err) {

            }
        });

    })

    $(".rating input").on('click', function (e) {
        window.value = $(this).val();
        window.productid = "{{product.id}}"
        window.isClicked = true;
    });

    $("#review-submit").on('click', function (e) {
        e.preventDefault();
        let value = window.value
        let productid = window.productid
        if (isClicked) {
            $.ajax({
                type: 'POST',
                url: '{% url "review:post_review"%}',
                data: {
                    productid: productid,
                    rating: value,
                    review_text: $('#review-text').val(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                },
                success: function (json) {
                    console.log($('#review-text').val(), )
                    location.reload()
                },
                error: function (xhr, errmsg, err) {

                }

            });
        }
    });
</script>
{% endblock content %}